url: https://erayfasol.github.io/ERayFaSol-portfolio/
baseurl:

# Site settings
title: Data Scientist | Data Analyst | MLops
email: ejfrancos99@gmail.com  
description: "Portafolio personal como cientifico de datos"


# Team names, titles and social links
people:
- name: Eduardo Franco
  pic: 1
  position: Cientifico de datos
  social:
    - title: LinkedIn
      url: https://www.linkedin.com/in/eduardo-j-franco-s/
    - title: GitHub
      url: https://github.com/ErayFaSol

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/eduardo-j-franco-s/
  - title: github
    url: https://github.com/ErayFaSol

# Postal address (add as many lines as necessary)
address:
  - line: Mexico
  - line: Puerto vallarta

# Build settings
markdown: kramdown
permalink: pretty